import { resolveDashboardModuleRoutePath } from "@/features/dashboard/shared/dashboardRouteTargets";
import type { DashboardDecorOrbConfig, DashboardEntranceOrbConfig } from "./dashboardHome.types";

export const dashboardEntranceOrbs: DashboardEntranceOrbConfig[] = [
  {
    key: "entrance-tasks",
    module: "tasks",
    label: "任务",
    color: "var(--cc-module-task)",
    glow: "var(--cc-module-task-glow)",
    orbitRadius: 286,
    orbitSpeed: 2.2,
    orbitOffset: 264,
    route: resolveDashboardModuleRoutePath("tasks"),
    size: 66,
  },
  {
    key: "entrance-notes",
    module: "notes",
    label: "便签",
    color: "var(--cc-module-notes)",
    glow: "var(--cc-module-notes-glow)",
    orbitRadius: 192,
    orbitSpeed: 1.76,
    orbitOffset: 28,
    route: resolveDashboardModuleRoutePath("notes"),
    size: 58,
  },
  {
    key: "entrance-memory",
    module: "memory",
    label: "镜子",
    color: "var(--cc-module-memory)",
    glow: "var(--cc-module-memory-glow)",
    orbitRadius: 278,
    orbitSpeed: 1.5,
    orbitOffset: 132,
    route: resolveDashboardModuleRoutePath("memory"),
    size: 56,
  },
  {
    key: "entrance-safety",
    module: "safety",
    label: "安全",
    color: "var(--cc-module-safety)",
    glow: "var(--cc-module-safety-glow)",
    orbitRadius: 332,
    orbitSpeed: 1.22,
    orbitOffset: 324,
    route: resolveDashboardModuleRoutePath("safety"),
    size: 58,
  },
];

export const dashboardDecorOrbs: DashboardDecorOrbConfig[] = [
  {
    key: "decor-1",
    module: "tasks",
    label: "drift-1",
    color: "color-mix(in srgb, var(--cc-module-task) 78%, var(--cc-ink) 22%)",
    glow: "color-mix(in srgb, var(--cc-module-task) 18%, transparent)",
    orbitRadius: 220,
    orbitSpeed: 1.1,
    orbitOffset: 12,
    size: 18,
  },
  {
    key: "decor-2",
    module: "notes",
    label: "drift-2",
    color: "color-mix(in srgb, var(--cc-module-notes) 82%, var(--cc-ink) 18%)",
    glow: "color-mix(in srgb, var(--cc-module-notes) 12%, transparent)",
    orbitRadius: 234,
    orbitSpeed: 0.9,
    orbitOffset: 80,
    size: 14,
  },
  {
    key: "decor-3",
    module: "memory",
    label: "drift-3",
    color: "color-mix(in srgb, var(--cc-module-memory) 80%, var(--cc-ink) 20%)",
    glow: "color-mix(in srgb, var(--cc-module-memory) 12%, transparent)",
    orbitRadius: 242,
    orbitSpeed: 0.84,
    orbitOffset: 150,
    size: 16,
  },
  {
    key: "decor-4",
    module: "safety",
    label: "drift-4",
    color: "color-mix(in srgb, var(--cc-module-safety) 80%, var(--cc-ink) 20%)",
    glow: "color-mix(in srgb, var(--cc-module-safety) 12%, transparent)",
    orbitRadius: 250,
    orbitSpeed: 0.72,
    orbitOffset: 220,
    size: 14,
  },
  {
    key: "decor-5",
    module: "tasks",
    label: "drift-5",
    color: "color-mix(in srgb, var(--cc-module-task) 70%, var(--cc-ink) 30%)",
    glow: "color-mix(in srgb, var(--cc-module-task) 10%, transparent)",
    orbitRadius: 266,
    orbitSpeed: 0.64,
    orbitOffset: 288,
    size: 12,
  },
  {
    key: "decor-6",
    module: "notes",
    label: "drift-6",
    color: "color-mix(in srgb, var(--cc-module-notes) 70%, var(--cc-ink) 30%)",
    glow: "color-mix(in srgb, var(--cc-module-notes) 10%, transparent)",
    orbitRadius: 276,
    orbitSpeed: 0.58,
    orbitOffset: 338,
    size: 10,
  },
];

export const dashboardModuleColors = {
  tasks: { color: "var(--cc-module-task)", glow: "var(--cc-module-task-glow)" },
  notes: { color: "var(--cc-module-notes)", glow: "var(--cc-module-notes-glow)" },
  memory: { color: "var(--cc-module-memory)", glow: "var(--cc-module-memory-glow)" },
  safety: { color: "var(--cc-module-safety)", glow: "var(--cc-module-safety-glow)" },
} as const;
