import type { ShellBallMotionConfig, ShellBallVisualState } from "./shellBall.types";

export const shellBallMotionMap = {
  idle: {
    accentTone: "slate",
    wingMode: "rest",
    ringMode: "hidden",
    eyeMode: "soft",
    bodyScale: 1,
    bodyTiltDeg: -4,
    floatOffsetY: -10,
    floatDurationMs: 5200,
    breatheScale: 1.02,
    breatheDurationMs: 4200,
    wingLiftDeg: 6,
    wingSpreadPx: 2,
    wingDurationMs: 3200,
    tailSwingDeg: 8,
    tailDurationMs: 3600,
    crestLiftPx: 0,
    blinkDelayMs: 0,
    showAuthMarker: false,
  },
  hover_input: {
    accentTone: "sky",
    wingMode: "lift",
    ringMode: "hidden",
    eyeMode: "curious",
    bodyScale: 1.04,
    bodyTiltDeg: -10,
    floatOffsetY: -14,
    floatDurationMs: 3600,
    breatheScale: 1.025,
    breatheDurationMs: 3200,
    wingLiftDeg: 10,
    wingSpreadPx: 6,
    wingDurationMs: 2200,
    tailSwingDeg: 12,
    tailDurationMs: 2600,
    crestLiftPx: 2,
    blinkDelayMs: 180,
    showAuthMarker: false,
  },
  confirming_intent: {
    accentTone: "sky",
    wingMode: "lift",
    ringMode: "hidden",
    eyeMode: "focus",
    bodyScale: 1.03,
    bodyTiltDeg: -6,
    floatOffsetY: -12,
    floatDurationMs: 3200,
    breatheScale: 1.018,
    breatheDurationMs: 2800,
    wingLiftDeg: 12,
    wingSpreadPx: 4,
    wingDurationMs: 1800,
    tailSwingDeg: 10,
    tailDurationMs: 2200,
    crestLiftPx: 1,
    blinkDelayMs: 120,
    showAuthMarker: false,
  },
  processing: {
    accentTone: "teal",
    wingMode: "flutter",
    ringMode: "hidden",
    eyeMode: "focus",
    bodyScale: 1.05,
    bodyTiltDeg: 2,
    floatOffsetY: -16,
    floatDurationMs: 2200,
    breatheScale: 1.03,
    breatheDurationMs: 1800,
    wingLiftDeg: 18,
    wingSpreadPx: 8,
    wingDurationMs: 760,
    tailSwingDeg: 16,
    tailDurationMs: 1400,
    crestLiftPx: 3,
    blinkDelayMs: 80,
    showAuthMarker: false,
  },
  waiting_auth: {
    accentTone: "amber",
    wingMode: "tucked",
    ringMode: "hidden",
    eyeMode: "careful",
    bodyScale: 0.99,
    bodyTiltDeg: 1,
    floatOffsetY: -8,
    floatDurationMs: 4000,
    breatheScale: 1.012,
    breatheDurationMs: 3400,
    wingLiftDeg: 4,
    wingSpreadPx: 1,
    wingDurationMs: 2600,
    tailSwingDeg: 6,
    tailDurationMs: 3000,
    crestLiftPx: 0,
    blinkDelayMs: 220,
    showAuthMarker: true,
  },
  voice_listening: {
    accentTone: "sky",
    wingMode: "lift",
    ringMode: "listening",
    eyeMode: "listening",
    bodyScale: 1.02,
    bodyTiltDeg: -8,
    floatOffsetY: -14,
    floatDurationMs: 2400,
    breatheScale: 1.028,
    breatheDurationMs: 1900,
    wingLiftDeg: 10,
    wingSpreadPx: 6,
    wingDurationMs: 1600,
    tailSwingDeg: 12,
    tailDurationMs: 1800,
    crestLiftPx: 2,
    blinkDelayMs: 140,
    showAuthMarker: false,
  },
  voice_locked: {
    accentTone: "teal",
    wingMode: "lift",
    ringMode: "locked",
    eyeMode: "locked",
    bodyScale: 1.04,
    bodyTiltDeg: 0,
    floatOffsetY: -11,
    floatDurationMs: 1800,
    breatheScale: 1.016,
    breatheDurationMs: 1600,
    wingLiftDeg: 7,
    wingSpreadPx: 3,
    wingDurationMs: 1200,
    tailSwingDeg: 7,
    tailDurationMs: 1600,
    crestLiftPx: 1,
    blinkDelayMs: 100,
    showAuthMarker: false,
  },
} satisfies Record<ShellBallVisualState, ShellBallMotionConfig>;

export function getShellBallMotionConfig(visualState: ShellBallVisualState) {
  return shellBallMotionMap[visualState];
}
